package com.office.rebates.dal.dataobj;

import java.util.Date;

public class QuestionAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.qa_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Long qaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.user_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.root_qa_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Long rootQaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.parent_qa_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Long parentQaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.content
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.create_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.last_update_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.qa_id
     *
     * @return the value of question_answer.qa_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Long getQaId() {
        return qaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.qa_id
     *
     * @param qaId the value for question_answer.qa_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setQaId(Long qaId) {
        this.qaId = qaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.user_id
     *
     * @return the value of question_answer.user_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.user_id
     *
     * @param userId the value for question_answer.user_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.root_qa_id
     *
     * @return the value of question_answer.root_qa_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Long getRootQaId() {
        return rootQaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.root_qa_id
     *
     * @param rootQaId the value for question_answer.root_qa_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setRootQaId(Long rootQaId) {
        this.rootQaId = rootQaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.parent_qa_id
     *
     * @return the value of question_answer.parent_qa_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Long getParentQaId() {
        return parentQaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.parent_qa_id
     *
     * @param parentQaId the value for question_answer.parent_qa_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setParentQaId(Long parentQaId) {
        this.parentQaId = parentQaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.content
     *
     * @return the value of question_answer.content
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.content
     *
     * @param content the value for question_answer.content
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.create_time
     *
     * @return the value of question_answer.create_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.create_time
     *
     * @param createTime the value for question_answer.create_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.last_update_time
     *
     * @return the value of question_answer.last_update_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.last_update_time
     *
     * @param lastUpdateTime the value for question_answer.last_update_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}