package com.office.rebates.dal.dataobj;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RebatesBonusMockExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public RebatesBonusMockExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBonusMockIdIsNull() {
            addCriterion("bonus_mock_id is null");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdIsNotNull() {
            addCriterion("bonus_mock_id is not null");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdEqualTo(Long value) {
            addCriterion("bonus_mock_id =", value, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdNotEqualTo(Long value) {
            addCriterion("bonus_mock_id <>", value, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdGreaterThan(Long value) {
            addCriterion("bonus_mock_id >", value, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdGreaterThanOrEqualTo(Long value) {
            addCriterion("bonus_mock_id >=", value, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdLessThan(Long value) {
            addCriterion("bonus_mock_id <", value, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdLessThanOrEqualTo(Long value) {
            addCriterion("bonus_mock_id <=", value, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdIn(List<Long> values) {
            addCriterion("bonus_mock_id in", values, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdNotIn(List<Long> values) {
            addCriterion("bonus_mock_id not in", values, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdBetween(Long value1, Long value2) {
            addCriterion("bonus_mock_id between", value1, value2, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andBonusMockIdNotBetween(Long value1, Long value2) {
            addCriterion("bonus_mock_id not between", value1, value2, "bonusMockId");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("customer_name is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("customer_name =", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("customer_name <>", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("customer_name >", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("customer_name >=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("customer_name <", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("customer_name <=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("customer_name like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("customer_name not like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIn(List<String> values) {
            addCriterion("customer_name in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotIn(List<String> values) {
            addCriterion("customer_name not in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("customer_name between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("customer_name not between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileIsNull() {
            addCriterion("customer_mobile is null");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileIsNotNull() {
            addCriterion("customer_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileEqualTo(String value) {
            addCriterion("customer_mobile =", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotEqualTo(String value) {
            addCriterion("customer_mobile <>", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileGreaterThan(String value) {
            addCriterion("customer_mobile >", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileGreaterThanOrEqualTo(String value) {
            addCriterion("customer_mobile >=", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLessThan(String value) {
            addCriterion("customer_mobile <", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLessThanOrEqualTo(String value) {
            addCriterion("customer_mobile <=", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLike(String value) {
            addCriterion("customer_mobile like", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotLike(String value) {
            addCriterion("customer_mobile not like", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileIn(List<String> values) {
            addCriterion("customer_mobile in", values, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotIn(List<String> values) {
            addCriterion("customer_mobile not in", values, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileBetween(String value1, String value2) {
            addCriterion("customer_mobile between", value1, value2, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotBetween(String value1, String value2) {
            addCriterion("customer_mobile not between", value1, value2, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountIsNull() {
            addCriterion("rebates_amount is null");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountIsNotNull() {
            addCriterion("rebates_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountEqualTo(BigDecimal value) {
            addCriterion("rebates_amount =", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountNotEqualTo(BigDecimal value) {
            addCriterion("rebates_amount <>", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountGreaterThan(BigDecimal value) {
            addCriterion("rebates_amount >", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rebates_amount >=", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountLessThan(BigDecimal value) {
            addCriterion("rebates_amount <", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rebates_amount <=", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountIn(List<BigDecimal> values) {
            addCriterion("rebates_amount in", values, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountNotIn(List<BigDecimal> values) {
            addCriterion("rebates_amount not in", values, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rebates_amount between", value1, value2, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rebates_amount not between", value1, value2, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 25 14:41:39 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}