package com.office.rebates.dal.dataobj;

import java.util.Date;

public class RebatesArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_article.article_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_article.type
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_article.is_deleted
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_article.title
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_article.keywords
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_article.description
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_article.create_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_article.last_update_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_article.content
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_article.article_id
     *
     * @return the value of rebates_article.article_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_article.article_id
     *
     * @param articleId the value for rebates_article.article_id
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_article.type
     *
     * @return the value of rebates_article.type
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_article.type
     *
     * @param type the value for rebates_article.type
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_article.is_deleted
     *
     * @return the value of rebates_article.is_deleted
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_article.is_deleted
     *
     * @param isDeleted the value for rebates_article.is_deleted
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_article.title
     *
     * @return the value of rebates_article.title
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_article.title
     *
     * @param title the value for rebates_article.title
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_article.keywords
     *
     * @return the value of rebates_article.keywords
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_article.keywords
     *
     * @param keywords the value for rebates_article.keywords
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_article.description
     *
     * @return the value of rebates_article.description
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_article.description
     *
     * @param description the value for rebates_article.description
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_article.create_time
     *
     * @return the value of rebates_article.create_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_article.create_time
     *
     * @param createTime the value for rebates_article.create_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_article.last_update_time
     *
     * @return the value of rebates_article.last_update_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_article.last_update_time
     *
     * @param lastUpdateTime the value for rebates_article.last_update_time
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_article.content
     *
     * @return the value of rebates_article.content
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_article.content
     *
     * @param content the value for rebates_article.content
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}