package com.office.rebates.dal.dataobj;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RebatesOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public RebatesOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSalesIdIsNull() {
            addCriterion("sales_id is null");
            return (Criteria) this;
        }

        public Criteria andSalesIdIsNotNull() {
            addCriterion("sales_id is not null");
            return (Criteria) this;
        }

        public Criteria andSalesIdEqualTo(Long value) {
            addCriterion("sales_id =", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdNotEqualTo(Long value) {
            addCriterion("sales_id <>", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdGreaterThan(Long value) {
            addCriterion("sales_id >", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sales_id >=", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdLessThan(Long value) {
            addCriterion("sales_id <", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdLessThanOrEqualTo(Long value) {
            addCriterion("sales_id <=", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdIn(List<Long> values) {
            addCriterion("sales_id in", values, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdNotIn(List<Long> values) {
            addCriterion("sales_id not in", values, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdBetween(Long value1, Long value2) {
            addCriterion("sales_id between", value1, value2, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdNotBetween(Long value1, Long value2) {
            addCriterion("sales_id not between", value1, value2, "salesId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdIsNull() {
            addCriterion("soho3q_order_id is null");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdIsNotNull() {
            addCriterion("soho3q_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdEqualTo(Long value) {
            addCriterion("soho3q_order_id =", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdNotEqualTo(Long value) {
            addCriterion("soho3q_order_id <>", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdGreaterThan(Long value) {
            addCriterion("soho3q_order_id >", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("soho3q_order_id >=", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdLessThan(Long value) {
            addCriterion("soho3q_order_id <", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("soho3q_order_id <=", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdIn(List<Long> values) {
            addCriterion("soho3q_order_id in", values, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdNotIn(List<Long> values) {
            addCriterion("soho3q_order_id not in", values, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdBetween(Long value1, Long value2) {
            addCriterion("soho3q_order_id between", value1, value2, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("soho3q_order_id not between", value1, value2, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileIsNull() {
            addCriterion("customer_mobile is null");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileIsNotNull() {
            addCriterion("customer_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileEqualTo(String value) {
            addCriterion("customer_mobile =", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotEqualTo(String value) {
            addCriterion("customer_mobile <>", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileGreaterThan(String value) {
            addCriterion("customer_mobile >", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileGreaterThanOrEqualTo(String value) {
            addCriterion("customer_mobile >=", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLessThan(String value) {
            addCriterion("customer_mobile <", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLessThanOrEqualTo(String value) {
            addCriterion("customer_mobile <=", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileLike(String value) {
            addCriterion("customer_mobile like", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotLike(String value) {
            addCriterion("customer_mobile not like", value, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileIn(List<String> values) {
            addCriterion("customer_mobile in", values, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotIn(List<String> values) {
            addCriterion("customer_mobile not in", values, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileBetween(String value1, String value2) {
            addCriterion("customer_mobile between", value1, value2, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerMobileNotBetween(String value1, String value2) {
            addCriterion("customer_mobile not between", value1, value2, "customerMobile");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("customer_name is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("customer_name =", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("customer_name <>", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("customer_name >", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("customer_name >=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("customer_name <", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("customer_name <=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("customer_name like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("customer_name not like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIn(List<String> values) {
            addCriterion("customer_name in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotIn(List<String> values) {
            addCriterion("customer_name not in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("customer_name between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("customer_name not between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyIsNull() {
            addCriterion("customer_company is null");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyIsNotNull() {
            addCriterion("customer_company is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyEqualTo(String value) {
            addCriterion("customer_company =", value, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyNotEqualTo(String value) {
            addCriterion("customer_company <>", value, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyGreaterThan(String value) {
            addCriterion("customer_company >", value, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("customer_company >=", value, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyLessThan(String value) {
            addCriterion("customer_company <", value, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyLessThanOrEqualTo(String value) {
            addCriterion("customer_company <=", value, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyLike(String value) {
            addCriterion("customer_company like", value, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyNotLike(String value) {
            addCriterion("customer_company not like", value, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyIn(List<String> values) {
            addCriterion("customer_company in", values, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyNotIn(List<String> values) {
            addCriterion("customer_company not in", values, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyBetween(String value1, String value2) {
            addCriterion("customer_company between", value1, value2, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyNotBetween(String value1, String value2) {
            addCriterion("customer_company not between", value1, value2, "customerCompany");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayIsNull() {
            addCriterion("customer_alipay is null");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayIsNotNull() {
            addCriterion("customer_alipay is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayEqualTo(String value) {
            addCriterion("customer_alipay =", value, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayNotEqualTo(String value) {
            addCriterion("customer_alipay <>", value, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayGreaterThan(String value) {
            addCriterion("customer_alipay >", value, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayGreaterThanOrEqualTo(String value) {
            addCriterion("customer_alipay >=", value, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayLessThan(String value) {
            addCriterion("customer_alipay <", value, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayLessThanOrEqualTo(String value) {
            addCriterion("customer_alipay <=", value, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayLike(String value) {
            addCriterion("customer_alipay like", value, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayNotLike(String value) {
            addCriterion("customer_alipay not like", value, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayIn(List<String> values) {
            addCriterion("customer_alipay in", values, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayNotIn(List<String> values) {
            addCriterion("customer_alipay not in", values, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayBetween(String value1, String value2) {
            addCriterion("customer_alipay between", value1, value2, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andCustomerAlipayNotBetween(String value1, String value2) {
            addCriterion("customer_alipay not between", value1, value2, "customerAlipay");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(String value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(String value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(String value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(String value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLike(String value) {
            addCriterion("order_type like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotLike(String value) {
            addCriterion("order_type not like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<String> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<String> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(String value1, String value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(String value1, String value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andPorjectIdIsNull() {
            addCriterion("porject_id is null");
            return (Criteria) this;
        }

        public Criteria andPorjectIdIsNotNull() {
            addCriterion("porject_id is not null");
            return (Criteria) this;
        }

        public Criteria andPorjectIdEqualTo(String value) {
            addCriterion("porject_id =", value, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdNotEqualTo(String value) {
            addCriterion("porject_id <>", value, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdGreaterThan(String value) {
            addCriterion("porject_id >", value, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("porject_id >=", value, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdLessThan(String value) {
            addCriterion("porject_id <", value, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdLessThanOrEqualTo(String value) {
            addCriterion("porject_id <=", value, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdLike(String value) {
            addCriterion("porject_id like", value, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdNotLike(String value) {
            addCriterion("porject_id not like", value, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdIn(List<String> values) {
            addCriterion("porject_id in", values, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdNotIn(List<String> values) {
            addCriterion("porject_id not in", values, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdBetween(String value1, String value2) {
            addCriterion("porject_id between", value1, value2, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectIdNotBetween(String value1, String value2) {
            addCriterion("porject_id not between", value1, value2, "porjectId");
            return (Criteria) this;
        }

        public Criteria andPorjectNameIsNull() {
            addCriterion("porject_name is null");
            return (Criteria) this;
        }

        public Criteria andPorjectNameIsNotNull() {
            addCriterion("porject_name is not null");
            return (Criteria) this;
        }

        public Criteria andPorjectNameEqualTo(String value) {
            addCriterion("porject_name =", value, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameNotEqualTo(String value) {
            addCriterion("porject_name <>", value, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameGreaterThan(String value) {
            addCriterion("porject_name >", value, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("porject_name >=", value, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameLessThan(String value) {
            addCriterion("porject_name <", value, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameLessThanOrEqualTo(String value) {
            addCriterion("porject_name <=", value, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameLike(String value) {
            addCriterion("porject_name like", value, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameNotLike(String value) {
            addCriterion("porject_name not like", value, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameIn(List<String> values) {
            addCriterion("porject_name in", values, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameNotIn(List<String> values) {
            addCriterion("porject_name not in", values, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameBetween(String value1, String value2) {
            addCriterion("porject_name between", value1, value2, "porjectName");
            return (Criteria) this;
        }

        public Criteria andPorjectNameNotBetween(String value1, String value2) {
            addCriterion("porject_name not between", value1, value2, "porjectName");
            return (Criteria) this;
        }

        public Criteria andCheckinDateIsNull() {
            addCriterion("checkin_date is null");
            return (Criteria) this;
        }

        public Criteria andCheckinDateIsNotNull() {
            addCriterion("checkin_date is not null");
            return (Criteria) this;
        }

        public Criteria andCheckinDateEqualTo(Date value) {
            addCriterionForJDBCDate("checkin_date =", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("checkin_date <>", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateGreaterThan(Date value) {
            addCriterionForJDBCDate("checkin_date >", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("checkin_date >=", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateLessThan(Date value) {
            addCriterionForJDBCDate("checkin_date <", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("checkin_date <=", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateIn(List<Date> values) {
            addCriterionForJDBCDate("checkin_date in", values, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("checkin_date not in", values, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("checkin_date between", value1, value2, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("checkin_date not between", value1, value2, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateIsNull() {
            addCriterion("checkout_date is null");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateIsNotNull() {
            addCriterion("checkout_date is not null");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateEqualTo(Date value) {
            addCriterionForJDBCDate("checkout_date =", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("checkout_date <>", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateGreaterThan(Date value) {
            addCriterionForJDBCDate("checkout_date >", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("checkout_date >=", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateLessThan(Date value) {
            addCriterionForJDBCDate("checkout_date <", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("checkout_date <=", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateIn(List<Date> values) {
            addCriterionForJDBCDate("checkout_date in", values, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("checkout_date not in", values, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("checkout_date between", value1, value2, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("checkout_date not between", value1, value2, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthIsNull() {
            addCriterion("period_month is null");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthIsNotNull() {
            addCriterion("period_month is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthEqualTo(Integer value) {
            addCriterion("period_month =", value, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthNotEqualTo(Integer value) {
            addCriterion("period_month <>", value, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthGreaterThan(Integer value) {
            addCriterion("period_month >", value, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("period_month >=", value, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthLessThan(Integer value) {
            addCriterion("period_month <", value, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthLessThanOrEqualTo(Integer value) {
            addCriterion("period_month <=", value, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthIn(List<Integer> values) {
            addCriterion("period_month in", values, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthNotIn(List<Integer> values) {
            addCriterion("period_month not in", values, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthBetween(Integer value1, Integer value2) {
            addCriterion("period_month between", value1, value2, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("period_month not between", value1, value2, "periodMonth");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekIsNull() {
            addCriterion("period_week is null");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekIsNotNull() {
            addCriterion("period_week is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekEqualTo(Integer value) {
            addCriterion("period_week =", value, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekNotEqualTo(Integer value) {
            addCriterion("period_week <>", value, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekGreaterThan(Integer value) {
            addCriterion("period_week >", value, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("period_week >=", value, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekLessThan(Integer value) {
            addCriterion("period_week <", value, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekLessThanOrEqualTo(Integer value) {
            addCriterion("period_week <=", value, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekIn(List<Integer> values) {
            addCriterion("period_week in", values, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekNotIn(List<Integer> values) {
            addCriterion("period_week not in", values, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekBetween(Integer value1, Integer value2) {
            addCriterion("period_week between", value1, value2, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andPeriodWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("period_week not between", value1, value2, "periodWeek");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountIsNull() {
            addCriterion("lease_amount is null");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountIsNotNull() {
            addCriterion("lease_amount is not null");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountEqualTo(Integer value) {
            addCriterion("lease_amount =", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountNotEqualTo(Integer value) {
            addCriterion("lease_amount <>", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountGreaterThan(Integer value) {
            addCriterion("lease_amount >", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("lease_amount >=", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountLessThan(Integer value) {
            addCriterion("lease_amount <", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountLessThanOrEqualTo(Integer value) {
            addCriterion("lease_amount <=", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountIn(List<Integer> values) {
            addCriterion("lease_amount in", values, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountNotIn(List<Integer> values) {
            addCriterion("lease_amount not in", values, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountBetween(Integer value1, Integer value2) {
            addCriterion("lease_amount between", value1, value2, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("lease_amount not between", value1, value2, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountIsNull() {
            addCriterion("deposit_amount is null");
            return (Criteria) this;
        }

        public Criteria andDepositAmountIsNotNull() {
            addCriterion("deposit_amount is not null");
            return (Criteria) this;
        }

        public Criteria andDepositAmountEqualTo(Integer value) {
            addCriterion("deposit_amount =", value, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountNotEqualTo(Integer value) {
            addCriterion("deposit_amount <>", value, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountGreaterThan(Integer value) {
            addCriterion("deposit_amount >", value, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("deposit_amount >=", value, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountLessThan(Integer value) {
            addCriterion("deposit_amount <", value, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountLessThanOrEqualTo(Integer value) {
            addCriterion("deposit_amount <=", value, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountIn(List<Integer> values) {
            addCriterion("deposit_amount in", values, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountNotIn(List<Integer> values) {
            addCriterion("deposit_amount not in", values, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountBetween(Integer value1, Integer value2) {
            addCriterion("deposit_amount between", value1, value2, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andDepositAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("deposit_amount not between", value1, value2, "depositAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioIsNull() {
            addCriterion("rebates_ratio is null");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioIsNotNull() {
            addCriterion("rebates_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioEqualTo(BigDecimal value) {
            addCriterion("rebates_ratio =", value, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioNotEqualTo(BigDecimal value) {
            addCriterion("rebates_ratio <>", value, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioGreaterThan(BigDecimal value) {
            addCriterion("rebates_ratio >", value, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rebates_ratio >=", value, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioLessThan(BigDecimal value) {
            addCriterion("rebates_ratio <", value, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rebates_ratio <=", value, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioIn(List<BigDecimal> values) {
            addCriterion("rebates_ratio in", values, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioNotIn(List<BigDecimal> values) {
            addCriterion("rebates_ratio not in", values, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rebates_ratio between", value1, value2, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andRebatesRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rebates_ratio not between", value1, value2, "rebatesRatio");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebates_order
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 25 14:41:39 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebates_order
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}