package com.office.rebates.dal.dataobj;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RebatesBonusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public RebatesBonusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBonusIdIsNull() {
            addCriterion("bonus_id is null");
            return (Criteria) this;
        }

        public Criteria andBonusIdIsNotNull() {
            addCriterion("bonus_id is not null");
            return (Criteria) this;
        }

        public Criteria andBonusIdEqualTo(Long value) {
            addCriterion("bonus_id =", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdNotEqualTo(Long value) {
            addCriterion("bonus_id <>", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdGreaterThan(Long value) {
            addCriterion("bonus_id >", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdGreaterThanOrEqualTo(Long value) {
            addCriterion("bonus_id >=", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdLessThan(Long value) {
            addCriterion("bonus_id <", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdLessThanOrEqualTo(Long value) {
            addCriterion("bonus_id <=", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdIn(List<Long> values) {
            addCriterion("bonus_id in", values, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdNotIn(List<Long> values) {
            addCriterion("bonus_id not in", values, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdBetween(Long value1, Long value2) {
            addCriterion("bonus_id between", value1, value2, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdNotBetween(Long value1, Long value2) {
            addCriterion("bonus_id not between", value1, value2, "bonusId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andSalesIdIsNull() {
            addCriterion("sales_id is null");
            return (Criteria) this;
        }

        public Criteria andSalesIdIsNotNull() {
            addCriterion("sales_id is not null");
            return (Criteria) this;
        }

        public Criteria andSalesIdEqualTo(Long value) {
            addCriterion("sales_id =", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdNotEqualTo(Long value) {
            addCriterion("sales_id <>", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdGreaterThan(Long value) {
            addCriterion("sales_id >", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sales_id >=", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdLessThan(Long value) {
            addCriterion("sales_id <", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdLessThanOrEqualTo(Long value) {
            addCriterion("sales_id <=", value, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdIn(List<Long> values) {
            addCriterion("sales_id in", values, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdNotIn(List<Long> values) {
            addCriterion("sales_id not in", values, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdBetween(Long value1, Long value2) {
            addCriterion("sales_id between", value1, value2, "salesId");
            return (Criteria) this;
        }

        public Criteria andSalesIdNotBetween(Long value1, Long value2) {
            addCriterion("sales_id not between", value1, value2, "salesId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdIsNull() {
            addCriterion("soho3q_order_id is null");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdIsNotNull() {
            addCriterion("soho3q_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdEqualTo(Long value) {
            addCriterion("soho3q_order_id =", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdNotEqualTo(Long value) {
            addCriterion("soho3q_order_id <>", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdGreaterThan(Long value) {
            addCriterion("soho3q_order_id >", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("soho3q_order_id >=", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdLessThan(Long value) {
            addCriterion("soho3q_order_id <", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("soho3q_order_id <=", value, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdIn(List<Long> values) {
            addCriterion("soho3q_order_id in", values, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdNotIn(List<Long> values) {
            addCriterion("soho3q_order_id not in", values, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdBetween(Long value1, Long value2) {
            addCriterion("soho3q_order_id between", value1, value2, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("soho3q_order_id not between", value1, value2, "soho3qOrderId");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumIsNull() {
            addCriterion("soho3q_order_num is null");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumIsNotNull() {
            addCriterion("soho3q_order_num is not null");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumEqualTo(String value) {
            addCriterion("soho3q_order_num =", value, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumNotEqualTo(String value) {
            addCriterion("soho3q_order_num <>", value, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumGreaterThan(String value) {
            addCriterion("soho3q_order_num >", value, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumGreaterThanOrEqualTo(String value) {
            addCriterion("soho3q_order_num >=", value, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumLessThan(String value) {
            addCriterion("soho3q_order_num <", value, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumLessThanOrEqualTo(String value) {
            addCriterion("soho3q_order_num <=", value, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumLike(String value) {
            addCriterion("soho3q_order_num like", value, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumNotLike(String value) {
            addCriterion("soho3q_order_num not like", value, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumIn(List<String> values) {
            addCriterion("soho3q_order_num in", values, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumNotIn(List<String> values) {
            addCriterion("soho3q_order_num not in", values, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumBetween(String value1, String value2) {
            addCriterion("soho3q_order_num between", value1, value2, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qOrderNumNotBetween(String value1, String value2) {
            addCriterion("soho3q_order_num not between", value1, value2, "soho3qOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumIsNull() {
            addCriterion("soho3q_confirmed_order_num is null");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumIsNotNull() {
            addCriterion("soho3q_confirmed_order_num is not null");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumEqualTo(String value) {
            addCriterion("soho3q_confirmed_order_num =", value, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumNotEqualTo(String value) {
            addCriterion("soho3q_confirmed_order_num <>", value, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumGreaterThan(String value) {
            addCriterion("soho3q_confirmed_order_num >", value, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumGreaterThanOrEqualTo(String value) {
            addCriterion("soho3q_confirmed_order_num >=", value, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumLessThan(String value) {
            addCriterion("soho3q_confirmed_order_num <", value, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumLessThanOrEqualTo(String value) {
            addCriterion("soho3q_confirmed_order_num <=", value, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumLike(String value) {
            addCriterion("soho3q_confirmed_order_num like", value, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumNotLike(String value) {
            addCriterion("soho3q_confirmed_order_num not like", value, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumIn(List<String> values) {
            addCriterion("soho3q_confirmed_order_num in", values, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumNotIn(List<String> values) {
            addCriterion("soho3q_confirmed_order_num not in", values, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumBetween(String value1, String value2) {
            addCriterion("soho3q_confirmed_order_num between", value1, value2, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andSoho3qConfirmedOrderNumNotBetween(String value1, String value2) {
            addCriterion("soho3q_confirmed_order_num not between", value1, value2, "soho3qConfirmedOrderNum");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountIsNull() {
            addCriterion("lease_amount is null");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountIsNotNull() {
            addCriterion("lease_amount is not null");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountEqualTo(Integer value) {
            addCriterion("lease_amount =", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountNotEqualTo(Integer value) {
            addCriterion("lease_amount <>", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountGreaterThan(Integer value) {
            addCriterion("lease_amount >", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("lease_amount >=", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountLessThan(Integer value) {
            addCriterion("lease_amount <", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountLessThanOrEqualTo(Integer value) {
            addCriterion("lease_amount <=", value, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountIn(List<Integer> values) {
            addCriterion("lease_amount in", values, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountNotIn(List<Integer> values) {
            addCriterion("lease_amount not in", values, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountBetween(Integer value1, Integer value2) {
            addCriterion("lease_amount between", value1, value2, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andLeaseAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("lease_amount not between", value1, value2, "leaseAmount");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxIsNull() {
            addCriterion("bonus_before_tax is null");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxIsNotNull() {
            addCriterion("bonus_before_tax is not null");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxEqualTo(Integer value) {
            addCriterion("bonus_before_tax =", value, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxNotEqualTo(Integer value) {
            addCriterion("bonus_before_tax <>", value, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxGreaterThan(Integer value) {
            addCriterion("bonus_before_tax >", value, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("bonus_before_tax >=", value, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxLessThan(Integer value) {
            addCriterion("bonus_before_tax <", value, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxLessThanOrEqualTo(Integer value) {
            addCriterion("bonus_before_tax <=", value, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxIn(List<Integer> values) {
            addCriterion("bonus_before_tax in", values, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxNotIn(List<Integer> values) {
            addCriterion("bonus_before_tax not in", values, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxBetween(Integer value1, Integer value2) {
            addCriterion("bonus_before_tax between", value1, value2, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusBeforeTaxNotBetween(Integer value1, Integer value2) {
            addCriterion("bonus_before_tax not between", value1, value2, "bonusBeforeTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxIsNull() {
            addCriterion("bonus_tax is null");
            return (Criteria) this;
        }

        public Criteria andBonusTaxIsNotNull() {
            addCriterion("bonus_tax is not null");
            return (Criteria) this;
        }

        public Criteria andBonusTaxEqualTo(Integer value) {
            addCriterion("bonus_tax =", value, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxNotEqualTo(Integer value) {
            addCriterion("bonus_tax <>", value, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxGreaterThan(Integer value) {
            addCriterion("bonus_tax >", value, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("bonus_tax >=", value, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxLessThan(Integer value) {
            addCriterion("bonus_tax <", value, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxLessThanOrEqualTo(Integer value) {
            addCriterion("bonus_tax <=", value, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxIn(List<Integer> values) {
            addCriterion("bonus_tax in", values, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxNotIn(List<Integer> values) {
            addCriterion("bonus_tax not in", values, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxBetween(Integer value1, Integer value2) {
            addCriterion("bonus_tax between", value1, value2, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusTaxNotBetween(Integer value1, Integer value2) {
            addCriterion("bonus_tax not between", value1, value2, "bonusTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxIsNull() {
            addCriterion("bonus_after_tax is null");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxIsNotNull() {
            addCriterion("bonus_after_tax is not null");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxEqualTo(Integer value) {
            addCriterion("bonus_after_tax =", value, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxNotEqualTo(Integer value) {
            addCriterion("bonus_after_tax <>", value, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxGreaterThan(Integer value) {
            addCriterion("bonus_after_tax >", value, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("bonus_after_tax >=", value, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxLessThan(Integer value) {
            addCriterion("bonus_after_tax <", value, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxLessThanOrEqualTo(Integer value) {
            addCriterion("bonus_after_tax <=", value, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxIn(List<Integer> values) {
            addCriterion("bonus_after_tax in", values, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxNotIn(List<Integer> values) {
            addCriterion("bonus_after_tax not in", values, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxBetween(Integer value1, Integer value2) {
            addCriterion("bonus_after_tax between", value1, value2, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andBonusAfterTaxNotBetween(Integer value1, Integer value2) {
            addCriterion("bonus_after_tax not between", value1, value2, "bonusAfterTax");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountIsNull() {
            addCriterion("rebates_amount is null");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountIsNotNull() {
            addCriterion("rebates_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountEqualTo(Integer value) {
            addCriterion("rebates_amount =", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountNotEqualTo(Integer value) {
            addCriterion("rebates_amount <>", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountGreaterThan(Integer value) {
            addCriterion("rebates_amount >", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("rebates_amount >=", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountLessThan(Integer value) {
            addCriterion("rebates_amount <", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountLessThanOrEqualTo(Integer value) {
            addCriterion("rebates_amount <=", value, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountIn(List<Integer> values) {
            addCriterion("rebates_amount in", values, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountNotIn(List<Integer> values) {
            addCriterion("rebates_amount not in", values, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountBetween(Integer value1, Integer value2) {
            addCriterion("rebates_amount between", value1, value2, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andRebatesAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("rebates_amount not between", value1, value2, "rebatesAmount");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebates_bonus
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 25 14:41:39 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebates_bonus
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}