package com.office.rebates.dal.dataobj;

public class RebatesGlobalLock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebates_global_lock.name
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebates_global_lock.name
     *
     * @return the value of rebates_global_lock.name
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebates_global_lock.name
     *
     * @param name the value for rebates_global_lock.name
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}