package com.office.rebates.dal.dao;

import com.office.rebates.dal.dataobj.QuestionAnswer;
import com.office.rebates.dal.dataobj.QuestionAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int countByExample(QuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int deleteByExample(QuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int deleteByPrimaryKey(Long qaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insert(QuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insertSelective(QuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    List<QuestionAnswer> selectByExample(QuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    QuestionAnswer selectByPrimaryKey(Long qaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") QuestionAnswer record, @Param("example") QuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExample(@Param("record") QuestionAnswer record, @Param("example") QuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByPrimaryKeySelective(QuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByPrimaryKey(QuestionAnswer record);
}