package com.office.rebates.dal.dao;

import com.office.rebates.dal.dataobj.RebatesBonusMock;
import com.office.rebates.dal.dataobj.RebatesBonusMockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebatesBonusMockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int countByExample(RebatesBonusMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int deleteByExample(RebatesBonusMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int deleteByPrimaryKey(Long bonusMockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insert(RebatesBonusMock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insertSelective(RebatesBonusMock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    List<RebatesBonusMock> selectByExample(RebatesBonusMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    RebatesBonusMock selectByPrimaryKey(Long bonusMockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") RebatesBonusMock record, @Param("example") RebatesBonusMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExample(@Param("record") RebatesBonusMock record, @Param("example") RebatesBonusMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByPrimaryKeySelective(RebatesBonusMock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_bonus_mock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByPrimaryKey(RebatesBonusMock record);
}