package com.office.rebates.dal.dao;

import com.office.rebates.dal.dataobj.RebatesUser;
import com.office.rebates.dal.dataobj.RebatesUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebatesUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:38 CST 2016
     */
    int countByExample(RebatesUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:38 CST 2016
     */
    int deleteByExample(RebatesUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:38 CST 2016
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insert(RebatesUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insertSelective(RebatesUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    List<RebatesUser> selectByExample(RebatesUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    RebatesUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") RebatesUser record, @Param("example") RebatesUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExample(@Param("record") RebatesUser record, @Param("example") RebatesUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByPrimaryKeySelective(RebatesUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_user
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByPrimaryKey(RebatesUser record);
}