package com.office.rebates.dal.dao;

import com.office.rebates.dal.dataobj.RebatesArticle;
import com.office.rebates.dal.dataobj.RebatesArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebatesArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int countByExample(RebatesArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int deleteByExample(RebatesArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int deleteByPrimaryKey(Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insert(RebatesArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insertSelective(RebatesArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    List<RebatesArticle> selectByExampleWithBLOBs(RebatesArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    List<RebatesArticle> selectByExample(RebatesArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    RebatesArticle selectByPrimaryKey(Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") RebatesArticle record, @Param("example") RebatesArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") RebatesArticle record, @Param("example") RebatesArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExample(@Param("record") RebatesArticle record, @Param("example") RebatesArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByPrimaryKeySelective(RebatesArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(RebatesArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_article
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByPrimaryKey(RebatesArticle record);
}