package com.office.rebates.dal.dao;

import com.office.rebates.dal.dataobj.RebatesGlobalLock;
import com.office.rebates.dal.dataobj.RebatesGlobalLockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebatesGlobalLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_global_lock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int countByExample(RebatesGlobalLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_global_lock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int deleteByExample(RebatesGlobalLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_global_lock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_global_lock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insert(RebatesGlobalLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_global_lock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int insertSelective(RebatesGlobalLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_global_lock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    List<RebatesGlobalLock> selectByExample(RebatesGlobalLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_global_lock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") RebatesGlobalLock record, @Param("example") RebatesGlobalLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebates_global_lock
     *
     * @mbggenerated Mon Jul 25 14:41:39 CST 2016
     */
    int updateByExample(@Param("record") RebatesGlobalLock record, @Param("example") RebatesGlobalLockExample example);
}